name: Update GitHub Stats

on:
  schedule:
    - cron: '0 */12 * * *' # Run automatically every 12 hours
  workflow_dispatch:      # Allow manual trigger from the GitHub Actions tab

permissions:
  contents: write         # Allows the Action to commit and push updates back to your repository

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Stats Table
        uses: axaysagathiya/gh-stats@v1
        with:
          token: ${{ secrets.GH_STATS_TOKEN }}
